
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vybzkelgcbrubfjhweeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5YnprZWxnY2JydWJmamh3ZWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzQxNjAsImV4cCI6MjA2MTg1MDE2MH0.Lv17QqaWf-6ACQ7jIJbnw-TW67LIdLE1s4x3dKeCFec";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});
